--liquibase formatted sql

--changeset author:initial-schema
CREATE TABLE SYNONYM_LIST (
    SY_ID INTEGER NOT NULL,
    SYNONYM_NAME VARCHAR(255) NOT NULL,
    SYNONYM_VALUE VARCHAR(255) NOT NULL,
    CSP_INSERT_TS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CSP_RECORD_START_DT DATE NOT NULL,
    CSP_RECORD_END_DT DATE NOT NULL
);
--rollback DROP TABLE SYNONYM_MASTER;
